trigger:
 branches:
  include:
    - 'main'
    - 'develop'
pr:
 branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Publish artefacts'
  inputs:
    command: 'publish'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
    projects: '**/*.csproj'
    arguments: '--configuration Release --output publish_output'

- task: ArchiveFiles@2
  displayName: 'Archive to ZIP'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.ArtifactsDirectory)/build$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.ArtifactsDirectory)/build$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(ee3efd09-b62b-44aa-9982-85306371f4b2)'
    appType: 'webAppLinux'
    WebAppName: 'api-cart'
    packageForLinux: '$(System.ArtifactsDirectory)/build$(Build.BuildId).zip'
    RuntimeStack: 'DOTNETCORE|6.0'

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure subscription 1(ee3efd09-b62b-44aa-9982-85306371f4b2)'
    appName: 'api-cart'
    resourceGroupName: 'api-cart_group'
    appSettings: |
      [
         {
          "name": "key1",
          "value": "valueabcd",
          "slotSetting": false
         },
         {
          "name": "key2",
          "value": "valueefgh",
          "slotSetting": true
         }
      ]
    